#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#+ Script to install r packages on fresh install
#+ Author: Mike Carter
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# [[ INSTALL {pak} FOR PKG MANAGEMENT ]]
install.packages("pak")

# [[ user packages ]]
pkgs <- c(
  # RCRAN packages
  "tidyverse",
  "easystats",
  "afex",
  "BUCSS",
  "compute.es",
  "countdown",
  "emmeans",
  "devtools",
  "diffdf",
  #"duckdb",
  "faux",
  "flextable",
  "fontawesome",
  "ftExtra",
  "GGally",
  "gganimate",
  "ggdist",
  "ggforce",
  "ggfortify",
  "ggrain",
  "ggpath",
  "ggpmisc",
  "ggpp",
  "ggprism",
  "ggpubr",
  "ggResidpanel",
  "googledrive",
  "grateful",
  "gt",
  "here",
  "Hmisc",
  "hrbrthemes",
  "infer",
  "interactionR",
  "kableExtra",
  "knitr",
  "languageserver",
  "linl",
  "lme4",
  "markdown",
  "marginaleffects",
  "marquee",
  "MBESS",
  "metafor",
  "miniUI",
  "modelsummary",
  "MOTE",
  "pagedown",
  "patchwork",
  "preregr",
  "prismatic",
  "puniform",
  "pwr",
  "pwrss",
  "qqplotr",
  "quarto",
  "readODS",
  "remotes",
  "renv",
  "rio",
  "rmarkdown",
  "robust",
  "Routliers",
  "scales",
  "sjPlot",
  "styler",
  "superb",
  "Superpower",
  "sysfonts",
  "tidybayes",
  "TOSTER",
  "trackdown",
  "usethis",
  "vitae",
  "workflowr",
  "WRS2",
  "yaml",
  # Github or development versions
  "cran/retimes@0.1-2", # archived package workaround
  "crsh/citr",
  "crsh/papaja@devel",
  "gadenbuie/rsthemes",
  "giocomai/ganttrify",
  "GRousselet/rogme",
  "hrbrmstr/hrbragg",
  "JLSteenwyk/ggpubfigs",
  "langenberg/powerANOVA",
  "liamgilbey/ggwaffle",
  "paleolimbot/rbbt",
  "profandyfield/discovr",
  "vincentarelbundock/tinytable" # already on CRAN but being actively developed
)
pak::pkg_install(pkgs)
