#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#+ Script to install r packages on fresh install
#+ Author: Mike Carter
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

##| install {pak} for package management
install.packages("pak")

##| user packages
pkgs <- c(
  #> RCRAN packages
  "tidyverse",
  "easystats",
  "afex",
  "BUCSS",
  "compute.es",
  "countdown",
  "emmeans",
  "devtools",
  "diffdf",
  "duckdb",
  "faux",
  "flextable",
  "fontawesome",
  "ftExtra",
  "GGally",
  "gganimate",
  "ggforce",
  "ggfortify",
  "ggrain",
  "ggpath",
  "ggpmisc",
  "ggpp",
  "ggprism",
  "ggpubr",
  "ggResidpanel",
  "googledrive",
  "gt",
  "here",
  "Hmisc",
  "hrbrthemes",
  "interactionR",
  "kableExtra",
  "knitr",
  "languageserver",
  "linl",
  "markdown",
  "marginaleffects",
  "MBESS",
  "metafor",
  "miniUI",
  "modelsummary",
  "MOTE",
  "pagedown",
  "patchwork",
  "preregr",
  "prismatic",
  "puniform",
  "pwr",
  "pwrss",
  "qqplotr",
  "quarto",
  "remotes",
  "renv",
  "rio",
  "rmarkdown",
  "robust",
  "Routliers",
  "scales",
  "sjPlot",
  "styler",
  "superb",
  "Superpower",
  "sysfonts",
  "TOSTER",
  "trackdown",
  "usethis",
  "vitae",
  "workflowr",
  "WRS2",
  "yaml",
  #> Github or development versions
  "cran/retimes@0.1-2", # archived package workaround
  "crsh/citr",
  "crsh/papaja@devel",
  "gadenbuie/rsthemes",
  "giocomai/ganttrify",
  "GRousselet/rogme",
  "hrbrmstr/hrbragg",
  "ismayc/thesisdown",
  "langenberg/powerANOVA",
  "liamgilbey/ggwaffle",
  "paleolimbot/rbbt",
  "paezha/macdown",
  "profandyfield/discovr",
  "vincentarelbundock/tinytable" # already on CRAN but being actively developed
)
pak::pkg_install(pkgs)
